#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

echo "Preparing and running the Fluid-Air participant..."

( cd Fluid-Air && ./Allrun )

# ----------------------------------------------------------------- end-of-file
