#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning..."

rm *.log
rm -rf precice-run

( cd Fluid &&  ./Allclean )
( cd Solid && rm -f *.xplt *.log *.json)
kill_blastfoam.sh

echo "Cleaning complete!"
#------------------------------------------------------------------------------
