#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

echo "Preparing and running the Fluid participant..."

( cd Fluid && ./Allrun )

# ----------------------------------------------------------------- end-of-file
